version: "3"

services:
  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./shema.sql:/docker-entrypoint-initdb.d/shema.sql
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=polls
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - result-tier
      - back-tier

  poll:
    restart: always
    build: ./poll
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    links:
        - redis

  worker:
    restart: always
    build: ./worker
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    networks:
      - back-tier
    links:
        - redis
        - db

  result:
    restart: always
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    networks:
      - result-tier
    links:
        - db

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: